<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE db [
<!ELEMENT db (user,passwd,host,name)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT passwd (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT name (#PCDATA)>
]>

<db>
	<user>zhiyuan</user>
	<passwd>zxjhzy826</passwd>
	<host>db4free.net</host>
	<name>zzaqi</name>
</db>
